name: Integration Test
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up xdb environment"
        run: wget https://raw.githubusercontent.com/xdblab/xdb/main/docker-compose/docker-compose-postgres14-example.yaml && docker compose -f docker-compose-postgres14-example.yaml up -d
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
      - run: git submodule update --init --recursive && sleep 10 && gradle build
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}