name: Test Build
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Test build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
      - run: git submodule update --init --recursive && sleep 10 && gradle build
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3